version: "3"
services:
  primary:
    build: ./mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodata:/data/db
      - ./mongo/crt:/crt
    ports:
      - 27017:27017
    networks:
      - mongoReplica
  secondary:
    build: ./mongo1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodata1:/data/db
      - ./mongo/crt:/crt
    ports:
      - 27018:27017
    networks:
      - mongoReplica

  # mongo-express:
  #   build: ./mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/  

volumes:
  mongodata:

networks:
  mongoReplica:
    driver: bridge
